name: Send SUPPORT and SEC notifications

on:
  workflow_dispatch:
    inputs:
      versions:
        description: "Release versions (comma-separated list, e.g. 7.17.0,7.16.3,7.15.8)"
        required: true

jobs:
  call-reusable-flow:
    uses: camunda/automation-platform-github-actions/.github/workflows/extract-issue-links.yml@main
    secrets: inherit
    with:
      versions: ${{ github.event.inputs.versions }}
      translation-notification-matcher: 7\.[0-9]+\.0
